### ISSUE TITLE
The Last King (Carcosa) story cards missing encounter codes

### ISSUE THREAD

**Issue by Filmire** [Kamalisk/arkhamdb-json-data#1075]
There are five cards in The Last King encounter that are double-sided encounter + story cards.  The story sides are missing their encounter codes.

Fix is to add:

```
encounter_code = "the_last_king"
encounter_name = "The Last King"
```

To these cards:

```
03065b
03066b
03067b
03068b
03069b
```

**Comment by fspoettel** [comment]
@Kamalisk  / @Filmire this issue can be closed.

**Comment by Filmire** [comment]
Confirmed that the encounter code is now listed on the cards above, thank you
