### ISSUE TITLE
Status of Machinations?

### ISSUE THREAD

**Issue by NoahPeres** [Kamalisk/arkhamdb-json-data#1165]
Just noticed that old mate machinations through time wasn't in here: anyone actively on this? If not I might type up some data myself in the next month or so if not too tricky!

**Comment by zzorba** [comment]
So far we've only typed up the cards that go in player decks.  We've love to have encounter cards, it's just a lot of typing when we can't start by scraping CGDB.

If you want to take a crack at typing them up, we'd welcome the pull request!

**Comment by NoahPeres** [comment]
Yeah fair fair I may take a look in the coming weeks thx for reply!

**Comment by drawntotheflame** [comment]
@NoahPeres @zzorba is a good person to ask questions to, or you can ask me as well, as I'm usually the person to correct other people's work!

**Comment by NoahPeres** [comment]
Beautiful well when I do get on this I'll make sure the online branch stays updated and try to ask questions on the way thanks for that tip! I'll try to be correct but we'll see how we go xD

**Comment by NoahPeres** [comment]
https://github.com/NoahPeres/arkhamdb-json-data/tree/noahp/machinations-encounter let me know if this is wildly off track: basically just copying the format of similar cards from other sets.

Also quickly ran into a bit of a funky edge case - the Tindalos card is weird since it is a double sided location where *technically* each side 'belongs to a different encounter set' (one side is single group, other is epic multi) - let me know how this should be done on the data side @zzorba @Kamalisk (will prob temporarily skip and come back to it)

**Comment by zzorba** [comment]
Wouldn't be an arkham scenario without breaking a rule or too.

So normally when we do double sided cards, we use 'links' but we typically hide one side of it, which makes it not show up in search.

I think in this case, it probably makes the most sense to just include the card twice (as ##### and ####b) and not bother linking them at all.  This way the two cards will show up when you page through by encounter-set properly (since they have their own encounter-position I assume?)

It's a bit gross, but them being two-sided actually has zero gameplay effect so I think that's probably the best course (cc: @drawntotheflame in case he feels differently)

**Comment by NoahPeres** [comment]
How about 'position' and 'encounter_position'? I'm guessing encounter position is somewhat arbitrary but that position should correspond to the number on the card itself (in this case 5), do these need to be unique? (as each side is position 5)

**Comment by NoahPeres** [comment]
another curveball I just thought of - River Docks (#87009) has 1 per investigator shroud (because why wouldn't it be needlessly compicated *facepalm*): would this require a modification of format.fancy_int?

**Comment by drawntotheflame** [comment]
> How about 'position' and 'encounter_position'? I'm guessing encounter position is somewhat arbitrary but that position should correspond to the number on the card itself (in this case 5), do these need to be unique? (as each side is position 5)

Position should be the same as the card number (though not card id), so a 1, 2 or 3 digit number.
Encounter position is used by the DB to determine where it shows the card. So if you have a set of 3 cards, 2 each, in an encounter set, labelling them by the 'first' card in each pair (1, 3, 5) lets the db know where to slot them. I *think* in this case you can put the same thing in... but we can take a look when it's live and double-check that's not caused problems. 



> another curveball I just thought of - River Docks (#87009) has 1 per investigator shroud (because why wouldn't it be needlessly compicated _facepalm_): would this require a modification of format.fancy_int?

I'd leave this just as the printed 1 shroud at the moment.

**Comment by fspoettel** [comment]
@NoahPeres / @Kamalisk  this issue can be closed.

**Comment by fspoettel** [comment]
@zzorba issue can be closed.
