### ISSUE TITLE
General Translation of ArkhamDB

### ISSUE THREAD

**Issue by TraXX0r** [Kamalisk/arkhamdb-json-data#1357]
Is there a way to set translations for non-card specific things?
I.e. all the stuff on the page itself like Cost, Test Icons, Health, Sanity, Willpower, Intellect, Combat and Agility? Likewise Deck Building, Bonded Cards, Related Cards

![ArkhamDB1](https://github.com/Kamalisk/arkhamdb-json-data/assets/115874505/7153a0c6-0766-4678-87a9-3b15128df574)
![ArkhamDB2](https://github.com/Kamalisk/arkhamdb-json-data/assets/115874505/8db150b0-a715-4f4a-8b50-9fb7115a3e3b)

**Comment by elkeinkrad** [comment]
Those translations are found in [arkhamDB](https://github.com/Kamalisk/arkhamdb) itself, and the files can be found [here](https://github.com/Kamalisk/arkhamdb/tree/arkham/src/AppBundle/Resources/translations).
 - `messages.00.xlf`
 - `FOSUserBundle.00.xlf`
where `00` is the code of the language, i.e., en. 

As I know, the id of trans-unit is not important (and will be changed by the maintainer at the server), so you could copy and translate them based on any translation language.

**Comment by fspoettel** [comment]
@zzorba this issue can be closed: it should be moved to arkhamdb repo.
