### ISSUE TITLE
Card Bewitching (card code - 10079) has an type_code of 'event'. Should be 'asset'

### ISSUE THREAD

**Issue by mickeytheq** [Kamalisk/arkhamdb-json-data#1363]
Can see https://arkhamdb.com/card/10079 is marked as an event

See below image shows it is a (permanent) asset.

![image](https://github.com/Kamalisk/arkhamdb-json-data/assets/42071167/b1316a22-0e61-4527-a903-348f8542d793)

**Comment by zzorba** [comment]
There's a PR open that addresses this and other typos from @TraXX0r

**Comment by Chr1Z93** [comment]
I think this can be closed? Type has been corrected

**Comment by fspoettel** [comment]
@mickeytheq / @Kamalisk this issue can be closed.

**Comment by fspoettel** [comment]
@zzorba this issue can be closed.
