### ISSUE TITLE
Extracurricular Activity scenario card marked as a Basic Weakness.

### ISSUE THREAD

**Issue by Shawnecy** [Kamalisk/arkhamdb-json-data#171]
The Dunwich Legacy scenario card, Extracurricular Activity (https://arkhamdb.com/card/02041), is marked as a Basic Weakness. I don't think scenario cards are also basic weaknesses (this is the only scenario marked as such).

**Comment by drawntotheflame** [comment]
This is very strange - I can't find where that Basic Weakness 'trait' text is coming from...

**Comment by Shawnecy** [comment]
Looks like this bug isn't against this repository: I just checked the card in the dwl_encounter.json, and it looks fine.

When I check it via the arkhamdb API (https://arkhamdb.com/api/public/card/02041), it definitely has the subtype_code of "basicweakness". I'm not sure what the relation is between this data and that API (I assume there's some connection), but somewhere it inherited that property value.

**Comment by Kamalisk** [comment]
I can clear the database up when I get the chance. Some data is not cleared up when removed, only added, so the subtype link once made exists forever.

**Comment by pdonate** [comment]
Looks like @Kamalisk fixed this via issue #965 .  This can be closed.

**Comment by fspoettel** [comment]
@zzorba this can be closed: implemented.
