### ISSUE TITLE
New Import of Data

### ISSUE THREAD

**Issue by wargfn** [Kamalisk/arkhamdb-json-data#185]
I am doing a new import of ArkhamDB Json data using:
php app/console app:import:std ../arkhamdb-json-data/

and I keep running into an  [Exception]
Missing key [shroud] in {"back_text":"As an additional cost for you to enter Catacombs, investigators at your location must spend
   1[per investigator] clues, as a group.","clues":2,"code":"03247","double_sided":true,"encounter_code":"the_pallid_mask","faction
  _code":"mythos","flavor":"Skulls and bones decorate the walls of this wide hallway in a macabre fashion.","illustrator":"Greg Bob
  rowski","name":"Catacombs","pack_code":"tpm","position":247,"quantity":1,"text":"<b>Forced<\/b> - When The Gate to Hell is reveal
  ed: Put the top 2 Catacombs in the Catacombs deck into play above and below The Gate to Hell.","type_code":"location"}

It is happening in  (Changing the encounter_code of Catacombs.

when I look at this pack tpm_encounter.json, doesn't look like any of these cards have a Shroud value.

**Comment by drawntotheflame** [comment]
Hello. I’ve put in shrouds and a bunch more corrections to tpm_encounter but they’ve not been pulled yet - I’m sure Kamalisk will do it in the next few days. Just hang tight.

**Comment by wargfn** [comment]
I just wanted to make sure I wasn't going crazy.
