### ISSUE TITLE
Encode the different types and quantities of 'Uses' into structured data.

### ISSUE THREAD

**Issue by zzorba** [Kamalisk/arkhamdb-json-data#209]
There are a number of cards that target a specific type of use (supplies, charges), and Akachi has a deckbuilding restriction that is currently implemented as a regex.

Would it be worth putting the concept of `uses` into the structured json?

Maybe something like:
```
uses: 'charges',
uses_count: 4,
```

Happy to make a PR if there's consensus.

**Comment by Kamalisk** [comment]
In theory we could, but I suspect it won't be the last of the weird card requirements. Could be anything like cards with a [fight] action, or some such. It also requires database changes to add those fields, unless you just wanted it in the raw json data.

**Comment by zzorba** [comment]
Yeah, you're right, there's going to be more stuff like this going forward.

I'll just parse it out locally when I read in the cards.
