### ISSUE TITLE
spoiler tag missing on a few cards

### ISSUE THREAD

**Issue by zzorba** [Kamalisk/arkhamdb-json-data#218]
Came across a few cards that don't have spoiler marked on them:

- The Scenario card for Miskatonic Museum (card 02118: https://arkhamdb.com/find?q=miskatonic+museum&sort=name&view=card&decks=all&spoilers=hide)
- Engram's Oath (card 03076b, back side of a last kind card, its standalone form has no spoiler tag: https://arkhamdb.com/find?q=engram&sort=name&view=list&decks=all)

The other last king VIP cards seem to have `spoiler` marked on the `linked_card` part, but not on the main card.  Just as an FYI, seems to be working okay on the side

**Comment by drawntotheflame** [comment]
Hello,

Scenario cards for MM and UAU were both missing 'encounter position: 1' which means they weren't getting marked as spoilers. I've added a request for that.

None of the backs of bystanders are marked as spoilers. Constance currently has the wrong back image.' @Kamalisk, can I put "encounter_position": x, on the b sides of cards?

**Comment by Kamalisk** [comment]
it should be fine to set that on both sides of the cards.
