### ISSUE TITLE
Translations ignored

### ISSUE THREAD

**Issue by Gizmo8690** [Kamalisk/arkhamdb-json-data#264]
Hi, on 9 April I have opened a pull request with many translations in italian, but my pull request was ignored and now is pending yet... Why?

**Comment by Kamalisk** [comment]
Your changes had conflicts. So looking over it, the newer ones did not. I was planning to use your changes to manually merge in those that were still needed, but that takes more time than just letting github merge them.

**Comment by Kamalisk** [comment]
I merged what I could. Sorry for not commenting about it sooner, did not have a lot of time and only just started to get italian added properly.
