### ISSUE TITLE
Translating Site wording

### ISSUE THREAD

**Issue by FeyrBert** [Kamalisk/arkhamdb-json-data#266]
Is it possible to have a file to translate things like the site menu, traits, slots and such?
It would be helpful for the search filters in other languages

**Comment by Kamalisk** [comment]
translating the UI would done elsewhere than these json files. The search page itself would probably need to be changed to dynamic, right now it is just selecting from the english data.

**Comment by Kamalisk** [comment]
those are in the database directly. Those are not currently supported for translation.
