### ISSUE TITLE
About the translation of TFA

### ISSUE THREAD

**Issue by FeyrBert** [Kamalisk/arkhamdb-json-data#342]
This is a question more then an issue: do I need to fill in the packs myself just copying the code of the card I'm referring to and using the standard scheme?
As there's no skeleton of the file already on the translation directory

**Comment by Kamalisk** [comment]
I can create the english skeleton for you. I can let you know when I have done so.

**Comment by FeyrBert** [comment]
Thanks mate :)
I have some spare time this week, if you manage to do it I think I can complete the set with the cards by sunday

**Comment by FeyrBert** [comment]
Otherwise I can just copy-paste the backbone from the other languages and put there the Italian version instead of using the usual English one

**Comment by Kamalisk** [comment]
https://github.com/Kamalisk/arkhamdb/blob/arkham/src/AppBundle/Resources/translations/messages.it.xlf

If you have time, can you translate some of these too? Trying to get translation of the UI itself working too, and having one translation to test with would be nice. (Replace the __words with the translation, removing the __ part)

**Comment by FeyrBert** [comment]
Sure, let me get home from work, I'll be on it and answer back :)
