### ISSUE TITLE
Website still in English

### ISSUE THREAD

**Issue by FeyrBert** [Kamalisk/arkhamdb-json-data#356]
Hey there,
Is there a particular reason why the Italian section is still in English in the last TFA packs, even though I translated those a couple weeks ago?

**Comment by Kamalisk** [comment]
I tend not to update the languages as quickly (just because they are merged into githib does not mean I have updated the servers). ALso tends to take longer while there are new packs waiting to be merged I tend to get behind on the updates.

**Comment by FeyrBert** [comment]
Ok cool :)
Thought there could be some issues on the work done and wanted to know if I could do something to fix it.
Cheers!

**Comment by FeyrBert** [comment]
Hey Allan,
There's an issue on the main page of the github where you write wich codes to use for the symbols on the card to show.
They are not [will],[lore] and [strength] as it is written, but [willpower], [intellect] and [combat]
So I have to rewrite all the Italian cards for the proper formatting.

Is there a way it can be done with a formula on the site?
Otherwise I'll just correct it one by one :)
