### ISSUE TITLE
Encounter code mismatch for K'n-yan

### ISSUE THREAD

**Issue by RoryBarclay** [Kamalisk/arkhamdb-json-data#358]
There is a mismatch with the encounter code used for K'n-yan (HotE)

- [encounters.json](https://github.com/Kamalisk/arkhamdb-json-data/blob/master/encounters.json#L299) uses the encounter code `k'n-yan`
- [hote_encounter.json](https://github.com/Kamalisk/arkhamdb-json-data/blob/master/encounters.json#L299) uses the encounter code `knyan` on lines 156, 176, 196, 215, 349, 366, 383, 401, 419, 437, 453.

This mismatch is preventing the encounter cards being imported on a clean install of arkhamdb, with the error
```
[Exception]                                                                                                                                                                                              
  Invalid code [knyan] for key [encounter_code] in {... "encounter_code":"knyan", ...}
```

Changing the encounter code in encounters.json to simply `knyan` allows the cards to be imported normally. Is this an appropriate change to make?

**Comment by drawntotheflame** [comment]
yeah, that's just a mismatch between the two files. It wasn't spotted between the import, the corrector and the checker-of-the-corrector (me). I'll put in a pull request now.

**Comment by RoryBarclay** [comment]
Thank you @drawntotheflame !
