### ISSUE TITLE
Wrong syntax (is this how it's called?)

### ISSUE THREAD

**Issue by FeyrBert** [Kamalisk/arkhamdb-json-data#367]
Hey Allan,
There's an issue on the main page of the github where you write wich codes to use for the symbols on the card to show.
They are not [will],[lore] and [strength] as it is written, but [willpower], [intellect] and [combat]
So I have to rewrite all the Italian cards for the proper formatting.

Is there a way it can be done with a formula on the site?
Otherwise I'll just correct it one by one :)

**Comment by Kamalisk** [comment]
I can probably fix it when I have time. but in general you should not change any text inside single [ square brackets as they are just keywords for icons. The readme is old and was what I originally did back when the game was just previewed.

**Comment by FeyrBert** [comment]
You're right, I was just coming back after a few months of not working on those files and went for the readme.
My bad!
As I was saying I can fix it if it's too much of a hassle for you to fix it, it would probably take me no more than an hour or so :)
