### ISSUE TITLE
Can we have a shared account to upload to the site?

### ISSUE THREAD

**Issue by FeyrBert** [Kamalisk/arkhamdb-json-data#390]
Hey there,
This was probably asked before but I didn't find it in the archived questions.
Is there a way we can have a shared account so we can upload the files directly on the site?
So that Kamalisk doesn't have to do it every time we upload, like, five cards with every new pack or we correct something.

Bonus question: how do I make multiple corrections in a single pull request?
I created 10 of those with the syntax fixes ^^"

**Comment by kamiben** [comment]
Hi FeyBert, 

I think it's not that simple, as currently, there is no admin interface to upload the files. The json files are inserted in the database directly with a script. So to give us access to update the cards, Allan would need to give access directly to the database and the scripts.

Maybe we could think of a script on top that would allow that, accessible from an authenticated page. Let's see what Allan thinks about this.

For your second question, you just have to fork the repository in your account (small button on top of this page and every page of the repo). That way you can do as many modification as you want. When finished, you can make one big pull request with all your small changes.

**Comment by FeyrBert** [comment]
Thank you for the answer!
I did create the fork for the files to work on them, but I didn't know I could what you're saying.
Next time I'll try that :)

Cheers!

**Comment by Kamalisk** [comment]
The translations arent updated yet because with new packs I wait until the english ones have been corrected before looking at anything else.
I would suggest you do the same for new pack translations, if you translate the incorrect files then errors might end up in the translation cards. 
Access to the server is unlikely, and anything 100% automated would probably not happen as then it would be possible for someone to simply insert random card data.

**Comment by kamiben** [comment]
Thanks for the feedback :)
Usually when we translate, we use the french cards in front of us, there is no 'real' translation going on. That way there is less room for error.
Is it more about formatting of special actions or token like [action] or replacing <br/> with \n ?
I'll be more careful and check what going on in the original files.

**Comment by fspoettel** [comment]
@zzorba I think we can close this one.
