### ISSUE TITLE
What is the preferred method for adding cards with faces of multiple types?

### ISSUE THREAD

**Issue by clayton-grey** [Kamalisk/arkhamdb-json-data#50]
For example, scenario act cards and asset cards which are one kind of card on one side and a different on the reverse face. A way to have a "/" name for the cards would be cool. Anyway, just want best practices before I finish the CoH card data.

**Comment by Kamalisk** [comment]
there is no sensible way to add them at the moment.

**Comment by clayton-grey** [comment]
So should I add them with an incremented new code after the last card? 

I assume "code" is the only unique value. Can card numbers overlap without breaking things? I can fudge it just to get the data in there if I know the tolerences.

**Comment by mplain** [comment]
Use code 00001 for front side, and 00001b for back side. See card #120

**Comment by clayton-grey** [comment]
Cool thanks.

PS - I accidentally committed some changes to the master without forking. Should I reapply them to a fork and do a pull or continue as is?

**Comment by Kamalisk** [comment]
You need to make have a branch to make a pull request.

**Comment by clayton-grey** [comment]
I guess I'll leave this open while you patch it.

**Comment by mplain** [comment]
Solved.
