### ISSUE TITLE
Cards from Undimensioned and Unseen are incorrectly labeled as in the Dunwich Legacy Deluxe

### ISSUE THREAD

**Issue by sacrelicious2** [Kamalisk/arkhamdb-json-data#58]
In particular, Quick Thinking (https://arkhamdb.com/card/02229), Rite of Seeking (4) (https://arkhamdb.com/card/02233) and Esoteric Formula (https://arkhamdb.com/card/02254) are all listed as being in Dunwich Legacy, instead of in the unreleased Undimensioned and Unseen mythos pack (source: https://www.fantasyflightgames.com/en/news/2017/1/25/undimensioned-and-unseen/)

This causes issues when deckbuilding with Dunwich Legacy.

**Comment by mplain** [comment]
Yep, submitted a fix already.

**Comment by mplain** [comment]
Fixed.
