### ISSUE TITLE
Across Space & Time missing

### ISSUE THREAD

**Issue by RisingSunStudios** [Kamalisk/arkhamdb-json-data#618]
This card [Across Space & Time](https://arkhamdb.com/find?q=across+time) appears to be missing from the cards endpoint.

https://arkhamdb.com/api/public/cards/ 

Cheers,

**Comment by akaan** [comment]
Hi,

It is an encounter card so you have to get it with https://arkhamdb.com/api/public/cards/?encounter=1

**Comment by RisingSunStudios** [comment]
Ah my bad, I thought I was searching for all cards - thanks!
