### ISSUE TITLE
Adding the rest of the investigator starter pack cards

### ISSUE THREAD

**Issue by Bzly** [Kamalisk/arkhamdb-json-data#696]
Does anyone have a fork where they're working on adding the rest of the leaked investigator starter cards? Text only, of course, until the official images come out. 

I've probably got enough time/willpower to add the remaining cards for one faction, and don't want to duplicate effort. Perhaps we could use this issue to co-ordinate?

Some people have got lucky and already received theirs, so there is no chance of text on the cards changing — I hope there's nothing against me adding some?

**Comment by zzorba** [comment]
We wait until the official street date to merge.  If you wanted to help proof this PR for typos though, that would be helpful as its a large card drop

https://github.com/Kamalisk/arkhamdb-json-data/pull/649

**Comment by Bzly** [comment]
Eep, somehow I completely glossed over that PR. Probably didn't expect it to be so far down/long ago, sorry! 

I was also wondering if you had a process like that (the waiting until official release), hence the third paragraph. Excellent, closing issue and I'll have a gander at #649.
