### ISSUE TITLE
Missing backs of cards

### ISSUE THREAD

**Issue by Sarnetsky** [Kamalisk/arkhamdb-json-data#701]
There are missing story cards on the back of GotA cards 83031—83036.

**Comment by zzorba** [comment]
Thanks for reporting, I opened up https://github.com/Kamalisk/arkhamdb-json-data/pull/702 to address.

The data is in the JSON, they just weren't linked up correctly.

**Comment by Sarnetsky** [comment]
@zzorba While we're at it, can you point me where's to look for the translation strings for the words like Victory or Vengeance in card texts? As far as I understand, these words are set globally(-ish?).

Or may be direct me where can I find answers for this kind of questions.

Thanks in advance!

**Comment by zzorba** [comment]
So I believe that stuff lives in the arkhamdb repo itself, under `src/AppBundle/Resources/translations/`.  However, it doesn't look like Victory/Vengeance were marked for translations.

I'll open a PR to suggest including them in the translation files.

**Comment by Vittek82** [comment]
I'll jump on the train and ask: ho do you translate slot names? On the Italian side, the core set cards are still showing slot names in english.

**Comment by Sarnetsky** [comment]
> I'll jump on the train and ask: ho do you translate slot names? On the Italian side, the core set cards are still showing slot names in english.

I second that.
