### ISSUE TITLE
Missing flavors and back names

### ISSUE THREAD

**Issue by Sarnetsky** [Kamalisk/arkhamdb-json-data#706]
There are no "back_name" entries on cards 02167—02174.
Is this a mistake or is it by design?

**Comment by zzorba** [comment]
Good catch -- looks like we missed this way back in the day. I'll open up a PR to address.

**Comment by Sarnetsky** [comment]
Oh, and flavors are missing on 02098 and 02107—02109

**Comment by zzorba** [comment]
Thanks for reporting, this will fix it https://github.com/Kamalisk/arkhamdb-json-data/pull/709
