### ISSUE TITLE
Missing 98001 and 98004

### ISSUE THREAD

**Issue by Sarnetsky** [Kamalisk/arkhamdb-json-data#726]
These pages show prompt “your query didn't match any card“:
https://arkhamdb.com/card/98001
https://arkhamdb.com/card/98004

**Comment by Kamalisk** [comment]
once we solve the "duplicate" problem, the hidden cards can be made viewable, until then they are hidden so we dont get into a mess. Caroyln is special because she was a book investigator first, so her appearance in a proper set is hidden instead.

**Comment by Sarnetsky** [comment]
May be a new attribute, "duplicate" would solve this: if it is true, the card is hidden in the lists of available cards (in deckbuilding) but shown in the set listings.

This also is gonna work with the ton of duplicates introduced in the investigator decks.

**Comment by Sarnetsky** [comment]
I have an idea (it may be obvious, but I'll spill it all the same)

Cards get a new attribute, "duplicate". Its value is a card code of the original card.
Duplicates are shown in pack listings, one can see them when addressed directly or through prev/next buttons.
FAQ sections, errata, reviews and comments are inherited from the original.
For everything related to deckbuilding, a non-null "duplicate" attribute is effectively the same as "hidden":"true".

It looks like arkhamdb needs this kind of thing for a ton of duplicates introduced in the investigator decks.

**Comment by fspoettel** [comment]
@zzorba I think we can close this one. We now have a system for marking duplicates and alt art investigators are also marked. The ids not working in arkhamdb is a site issue, not a data issue.
