### ISSUE TITLE
Importing Cards - problem

### ISSUE THREAD

**Issue by Morphium84** [Kamalisk/arkhamdb-json-data#734]
Hello. I get an error when trying to import arkhamdb-json-data. What could it be because of?

screenshot - https://prnt.sc/u7jr6j

> Importing Cards...
> 17:29:02 ERROR     [console] Error thrown while running command "app:import:std ark". Message: "No repository found at [arkpack/core]" ["exception" => Exception { …},"command" => "app:import:std ark","message" => "No repository found at [arkpack/core]"]
> 
> In ImportStdCommand.php line 861:
> 
>   No repository found at [arkpack/core]

**Comment by zzorba** [comment]
The first argument to import cards should be the path to the `arkhamdb-json-data` repo. This is mine for example, assuming arkhamdb and arkhamdb-json-data are in parallel folders:

```
php bin/console  app:import:std ../arkhamdb-json-data/
```

**Comment by Morphium84** [comment]
Thanks! And then, when importing, another error occurs.
Is there something wrong with the DB?

screenshot - https://prnt.sc/u7kyyp

> In PDOStatement.php line 123:

>  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'real_slot' cannot be null

**Comment by zzorba** [comment]
You might need to repull from the main repo & recreate the database scheme. There was a break I checked in last week, but its since been corrected I believe.

**Comment by Morphium84** [comment]
Thanks, helped!
