### ISSUE TITLE
Couple of mistakes noticed

### ISSUE THREAD

**Issue by Sarnetsky** [Kamalisk/arkhamdb-json-data#764]
https://arkhamdb.com/card/02041 has unneeded “Basic Weakness” type
https://arkhamdb.com/card/02122 has 2 [per investigator] clues while it should have just 2.

**Comment by drawntotheflame** [comment]
Hey @Sarnetsky are you on the MB discord for the game? One option is we add you to the scribes of Arkhamdb group on discord and you can liaise with some of the scribes directly?

**Comment by Sarnetsky** [comment]
@drawntotheflame No, I'm not on discord yet. Will gladly become a part of the team, what should I do?)

**Comment by drawntotheflame** [comment]
The discord is here: https://discord.gg/XXg5ZE

Send me a message to say hi - I'm zooeyglass#2816

**Comment by Bzly** [comment]
First of these is noted in #171. Card ID 02041 in the json data only has the "scenario" type. @Kamalisk mentioned needing to clear the database up as type information is only added to. 

Card ID 02122 is missing `"clues_fixed": true` — I have updated it in my fork and will submit a PR shortly.
