### ISSUE TITLE
Front and back side for location type cards mixed up

### ISSUE THREAD

**Issue by Warmduscher** [Kamalisk/arkhamdb-json-data#92]
Hi,
i think that the front and back sides of location based cards are mixed up. For example the two cards:

https://arkhamdb.com/card/02245
https://arkhamdb.com/card/01113

show that the back_flavor is sometimes on the wrong side (according to picture) and sometimes on the right side. Also i have a feeling, that it would be better if the front card is shows the unrevealed side of the card and the back side the revealed effects. Just like it is done with act and agenda cards.

regards,
Mike

**Comment by drawntotheflame** [comment]
I can work through and correct this but I think it's been inconsistent in the past. Kamalisk, how would you like it done? 'unrevealed' = back at the moment, because "text" refers, normally, to the main card text. Happy to work through and rectify as soon as I know which way to do it. 
F

**Comment by Kamalisk** [comment]
the back of locations is the unrevealed side (since it has no card number on it). 
The front of the location is the card with the number (the revealed side)

**Comment by drawntotheflame** [comment]
Great, thank you, I'll correct.

**Comment by Warmduscher** [comment]
thanks the both of you
