### ISSUE TITLE
octgn_id is missing in data files

### ISSUE THREAD

**Issue by Warmduscher** [Kamalisk/arkhamdb-json-data#93]
Hi,

it seems, that the data files doesn't contain the octgn_id. This attribute can be found through the API on arkhamdb.com.

How is the process of getting the octgn_id into arkhamdb.com? (I'm trying to extends the OCTGN Plugin with UAU and WDA)
Is there any other information missing in the JSON Files?

regards,
Mike

**Comment by Kamalisk** [comment]
there is a script which does it on my end, currently I run it manually. It grabs the octgn ids from the github repo.

**Comment by Warmduscher** [comment]
sound good for me. I forked gecko's octgn module and integrated the card data for uau and wda from your site using the API and some generated UUIDs. Probably during a weekend i'll finish up and issue a pull request.
