### ISSUE TITLE
Card data 03321a & 03321b are incorrect

### ISSUE THREAD

**Issue by pdonate** [Kamalisk/arkhamdb-json-data#959]
Card 03321a "Search For the Stranger (v.I)" has no backimagesrc, nor does it have linked_card or linked_to_code. This is an Act card, so it seems like it should have either a back image or link data.

Card 03321b "The Pallid Mask" image asset is incorrect. The card does have an imagesrc, and the path is correct (bundles/cards/03321b.jpg), but the actual .jpg is the wrong image.

03321b also has links to card 03321a, but it looks like the link is actually meant to go in the reverse direction. Please see rationale in details for card 03321a above.

Proposed Fix:

It looks like these two cards are meant to be paired in the same way that 01121a and 01121b are paired. If that's the case, I think this can be fixed by:

03321a:
- Add the correct link info to 03321b.
- Remove hidden: true attribute

03321b:
- Remove the link to 03321a
- Add hidden: true attribute
- Replace the imagesrc asset .jpg with the correct image

**Comment by pdonate** [comment]
![03321b](https://user-images.githubusercontent.com/43149038/120566818-f10b7b80-c3c4-11eb-99dd-60f3ef275d4d.jpg)

Attached the correct image asset for 03321b

**Comment by Kamalisk** [comment]
thanks for the detailed report. switched them around and put in the image.
