### ISSUE TITLE
EoE investigator deck building requirements

### ISSUE THREAD

**Issue by stoplis** [Kamalisk/arkhamdb-json-data#999]
The Edge of the Earth investigators deck building requirements are incorrect. They should all read “up to 5  **other** _insert class_ cards level 0” this is the same wording that should be applied to the tabooed version of Norman Withers (Ire of the Void).

**Comment by zzorba** [comment]
Thanks for reporting this, I'll push a correction. The website should be enforcing the rules correctly, with respect to dual class cards (we actually never implemented the old Norman rule, assuming it was a typo).
